# Generated by Django 3.0.6 on 2020-05-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfo',
            name='email',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
