# Generated by Django 3.0.6 on 2020-05-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0002_myinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfo',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
