# Generated by Django 3.0.6 on 2020-05-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0003_myinfo_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinfo',
            name='picture',
            field=models.BinaryField(null=True),
        ),
    ]
