# Generated by Django 3.0.6 on 2020-05-30 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0004_auto_20200530_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myinfo',
            name='picture',
        ),
    ]
